---
- name: Instalar y configurar nginx, Grafana y Prometheus
  hosts: localhost
  become: yes

  tasks:
    - name: Actualizar paquetes
      apt:
        update_cache: yes
        
    - name: Instalar dependencias
      apt:
        name:
          - curl
          - software-properties-common
        state: present

    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Instalar Prometheus
      apt:
        name: prometheus
        state: present

    - name: Instalar Grafana
      apt:
        name: grafana
        state: present

    - name: Iniciar y habilitar nginx
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Iniciar y habilitar Prometheus
      systemd:
        name: prometheus
        state: started
        enabled: yes

    - name: Iniciar y habilitar Grafana
      systemd:
        name: grafana-server
        state: started
        enabled: yes

    - name: Eliminar configuracion por defecto nginx
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Agregar configuracion nginx
      copy:
        src: provisioning/static-site-config
        dest: /etc/nginx/sites-available/
        owner: "{{ user }}"
        group: root
        mode: '0644'

    - name: Habilitar configuracion de nginx
      file:
        src: /etc/nginx/sites-available/static-site-config
        dest: /etc/nginx/sites-enabled/static-site-config
        state: link

    - name: Configurar firewall para Grafana y Prometheus
      ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - 3000  
        - 9090  

    - name: Reiniciar servicios para aplicar configuración
      systemd:
        name: "{{ item }}"
        state: restarted
      loop:
        - nginx
        - prometheus
        - grafana-server

        - name: Descargar nginx-prometheus-exporter
      get_url:
        url: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v1.1.0/nginx-prometheus-exporter_1.1.0_linux_amd64
        dest: /usr/local/bin/nginx-prometheus-exporter
        mode: '0755'

    - name: Crear servicio systemd para nginx-prometheus-exporter
      copy:
        dest: /etc/systemd/system/nginx-exporter.service
        content: |
          [Unit]
          Description=NGINX Prometheus Exporter
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/nginx-prometheus-exporter -nginx.scrape-uri http://127.0.0.1/nginx_status
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Habilitar e iniciar nginx-exporter
      systemd:
        name: nginx-exporter.service
        enabled: yes
        state: started
        daemon_reload: yes
    
    - name: Configurar Prometheus con job para nginx-exporter
      copy:
        src: provisioning/prometheus.yml
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus
        mode: '0644'
        
    - name: Reiniciar Prometheus para cargar nueva configuración
      systemd:
        name: prometheus
        state: restarted



    




