---
- name: Configurar servidor con Nginx, Prometheus y Grafana
  hosts: all
  become: true
  tasks:
    - name: Instalar Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Instalar dependencias para Prometheus y Grafana
      apt:
        name:
          - wget
          - curl
          - gnupg2
          - software-properties-common
        state: present
        update_cache: yes

    - name: Añadir repositorio de Prometheus (si es necesario)
      # Aquí puedes definir instalación personalizada, descarga de binarios, etc.

    - name: Añadir repositorio de Grafana
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present
      become: true

    - name: Añadir fuente de APT para Grafana
      apt_repository:
        repo: 'deb https://packages.grafana.com/oss/deb stable main'
        state: present

    - name: Instalar Grafana
      apt:
        name: grafana
        state: present
        update_cache: yes

    - name: Iniciar y habilitar servicios
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - nginx
        - grafana-server

      
