Vagrant.configure("2") do |config|

  config.vm.box = "rockylinux/8"
  config.vm.box_version = "10.0.0"
  config.vm.network "forwarded_port", guest: 80, host: 80

  config.vm.network "private_network", ip: "192.168.1.14"
  config.vm.network "public_network", use_dhcp_assigned_default_route: true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus= "4"
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook ="laybook.yml"
  end

end
